### ISSUE TITLE
New installation: caching issues

### ISSUE THREAD

**Issue by cord** [nemrutco/nova-global-filter#1]
when installing I need to do a hard reload a couple of times (?) before the filter widget was shown. The cards-request returned the filter card, but it was not visible. I guess due to the overloading of js resources?

**Comment by muzafferdede** [comment]
> I guess due to the overloading of js resources? 

I believe so. Nothing i know would cause such a thing considering what how this package works. All it does is broadcast the event and all the listers grabs the changes and do their thing with it. 

Perhaps you can do some more debugging in a fresh laravel app and see if it does the same thing?

**Comment by cord** [comment]
adding a version token to the resources would make sure the correct version is loaded?
