### ISSUE TITLE
Question: How to make filter compatible?

### ISSUE THREAD

**Issue by cord** [nemrutco/nova-global-filter#16]
e.g. following filter packages:

https://novapackages.com/packages/ampeco/nova-date-range-filter
https://novapackages.com/packages/rcknr/nova-multiselect-filter
https://novapackages.com/packages/klepak/nova-multiselect-filter
https://novapackages.com/packages/digital-creative/nova-pill-filter

are not showing up in the global filter - what needs to be done to make them work with the Global Filter?

**Comment by muzafferdede** [comment]
As i mentioned on [here](https://github.com/nemrutco/nova-global-filter#good-to-know), Nova's default metrics cards has been optimized by me to support global filter. 

For example you can check how ValueMetric has been optimized from following files:
- [FilterBehavior.js](resources/js/components/FilterBehavior.js)
- [ValueMetric.vue](resources/js/components/ValueMetric.vue)

Basically on emitter side you need to emit the changes, on filter side you need to listen these events and react to it.
