### ISSUE TITLE
Add empty value for filters

### ISSUE THREAD

**Issue by xoco70** [nemrutco/nova-global-filter#19]
Hi, 

When including a filter, it comes with a default value I don't know if it is applied, nor how it choose it.

To compare with Nova behaviour, Nova always include an empty value. This allows to add / remove filter easily.

Here, when I choose a filter, I cannot remove it. Even with 'reset', it reset to the first value of the list. 

There should have a -- first entry.

**Comment by muzafferdede** [comment]
Should be fixed by v1.0.5

**Comment by xoco70** [comment]
Yep, it worked. But now, ->inline() is broken!  ^^

**Comment by xoco70** [comment]
oooh, The fourth one is below the cards. I'll make you a screenshot

**Comment by xoco70** [comment]
![Screenshot from 2020-07-30 17-24-16](https://user-images.githubusercontent.com/5855577/88941740-acd1bb00-d289-11ea-972b-7c2e98bdaade.png)

Here the last field is : "Jusqu'au"

**Comment by muzafferdede** [comment]
For some reason, branches are mixed up. Just fixed by v1.1.0
