### ISSUE TITLE
Positioning of filter card

### ISSUE THREAD

**Issue by cord** [nemrutco/nova-global-filter#2]
Currently, the global filter card is always at the bottom regardless of the code order in the cards() method - would be great if we can control this? (I know there have been some issues with the way nova handles the order)

**Comment by muzafferdede** [comment]
should be fixed with `v1.0.1` Pls update and let me know if all good.

**Comment by cord** [comment]
Great! works!
![1 2020-05-01 13-45-46](https://user-images.githubusercontent.com/158588/80803267-15899880-8bb2-11ea-909f-a0d075e71a75.png)
