### ISSUE TITLE
Question: Is there a way to use predefined default value for the certain filter?

### ISSUE THREAD

**Issue by dpetrovaliev** [nemrutco/nova-global-filter#21]

**Comment by muzafferdede** [comment]
i think [Filter Default Values](https://nova.laravel.com/docs/3.0/filters/defining-filters.html#filter-default-values) on Nova docs might help you. you could define your default filter values as:

```php
/**
 * The default value of the filter.
 *
 * @var string
 */
public function default()
{
    return true;
}
```

**Comment by roadsend** [comment]
While a default does update the filter for the main panel- it does not change the metric card.  Defaults are ignored.

**Comment by MuzafferDede** [comment]
This issue will be fixed in next release.
