### ISSUE TITLE
global-filter-changed event is fired onChange and OnBlur

### ISSUE THREAD

**Issue by faizaajmal** [nemrutco/nova-global-filter#23]
When i use global date filter and pick my date from the datepicker. it fires same event onBlur and OnChange that creates two requests. How can i disable the event onBlur?
```
new NovaGlobalFilter([
                new DateFilter(), // Date Filter
            ]),
```

**Comment by MuzafferDede** [comment]
This should be fixed in next release. Please let me know if you have any issues after the new release.
