### ISSUE TITLE
DateFilter

### ISSUE THREAD

**Issue by CosmicodeStudio** [nemrutco/nova-global-filter#24]
I'm having some issues with this package, first the default in my DateFilter is not showing, while is showing if I add that to a resource. Second when I select a date is always showing the time as well, always 00:00:00, while inside the resource it only shows the date without the time.

**Comment by MuzafferDede** [comment]
I think you are parsing the date via `$value = Carbon::parse($value);` which will also include time... This package will only give you `Y-m-d` formatted date. Let me know if you still have issue on this.
