### ISSUE TITLE
can this also be used to apply a global filter to all resources themselves?

### ISSUE THREAD

**Issue by vesper8** [nemrutco/nova-global-filter#26]
I went looking for a global filter that would be applicable to all resources. All my resources belong to a "season" and I want to filter them all so it only ever shows data from one season at a time. Can your global filter be used this way? To be clear I'm not interested in using cards on any of my resources.

Thanks!

**Comment by MuzafferDede** [comment]
This packages only filters cards. It does not filter resources. You might want to check [this](https://novapackages.com/packages/square1-io/nova-metrics) one which could give you what you need.

**Comment by vesper8** [comment]
Thanks. I ended up getting something to work using the default value and the cache. I'll leave this snippet here for anyone else that finds this issue

```
<?php

namespace App\Nova\Filters;

use Illuminate\Http\Request;
use App\Models\Season;
use Laravel\Nova\Filters\Filter;

class SeasonFilter extends Filter
{
    public function apply(Request $request, $query, $value)
    {
        // ray('SeasonFilter', cache('NOVA-SEASON'));

        cache(['NOVA-SEASON' => $value], now()->addMinutes(60));

        return $query->where('season_id', $value)->get();
    }

    public function options(Request $request)
    {
        $seasons = Season::orderBy('id', 'desc')->get();

        return $seasons->pluck('id', 'name');
    }

    public function default()
    {
        return cache('NOVA-SEASON', config('defaults.latest_season_id'));
    }
}
```
