### ISSUE TITLE
Layout global filter

### ISSUE THREAD

**Issue by cord** [nemrutco/nova-global-filter#3]
currently, the global filter card consumes a lot of space.
Would be great to have a slim version

![1 2020-05-01 14-02-44](https://user-images.githubusercontent.com/158588/80804109-731ee480-8bb4-11ea-9277-40f5bdfdc7ad.png)
 or even some options to style like this:
![71813573-429dc280-307a-11ea-9238-a128968b8847](https://user-images.githubusercontent.com/158588/80804166-a5c8dd00-8bb4-11ea-8f02-b4af94a29c5c.png)

wonder if this could be achieved with allow the user to add some CSS classes or define a custom view?

**Comment by muzafferdede** [comment]
Maybe i could allow users to define as any other cards " w-1/3", "w-2/3" and by default full width as it is now.

**Comment by cord** [comment]
ah - I am thinking about the height of the card. I think it should be fullwidth "toolbar" rather than a card panel. And of course the width of the filter widgets and padding between them to make it more compact.

**Comment by muzafferdede** [comment]
I see your point. Hmm that's a bit tricky. Maybe there could be a accordion style as option to allow collapse toggle. But not sure if layout could be dynamic as your mention. I could define some classes for custom styling by user, but we still need to stick with a layout guideline. Let's get some feedback and we'll see what to do on this topic.

**Comment by cord** [comment]
maybe missing is a nova "slim" style where everything is less "fluffy"

**Comment by muzafferdede** [comment]
Yeah, i think there could be a better way to layout custom cards on pages but current way is limited by nova. Specially we are looping filters as there might be checkbox or other type of input elements. Let's see if we can come out with a good idea. Open to suggestions.

**Comment by muzafferdede** [comment]
And @cord i want to know all your use cases and needs if it's possible since the package idea come from you. So i can implement them as we go. So it would be great to collect some use cases and needs for a while and implement until we got a solid package. Thank you.

**Comment by cord** [comment]
@muzafferdede thanks again for your great work.

I think almost any Nova App could use a kind of interactive analytics dashboard / BI dashboard / (... https://powerbi.microsoft.com ...) , so I think this could be a (commercial?) package by itself. 

Am thinking of:

- configuration of dashboards with widgets, e.g. like this:
![csm - Laravel Schema Designer 2020-05-14 16-13-02](https://user-images.githubusercontent.com/158588/81945018-d3267980-95fd-11ea-83c3-dd6c0605454e.png)
(each widget can be configured for a data source, visualization.... - missing in the schema above)

- direct links to dashboard e.g. with https://github.com/dcasia/collapsible-resource-manager

- support for drill down
  - click on charts / legends sets filters to narrow down

- comprehensive data visualizations, supporting e.g. 
  - https://developers.google.com/chart/interactive/docs/gallery
  - https://www.amcharts.com/demos/
  - https://canvasjs.com/javascript-charts/
  - ...
- ETL framework to aggregate data

so once installed the developer just needs to create/configure datasources. Then dashboards can be configured with different widgets, default filter settings etc.

am happy to contribute with a nova setup for managing dashboards including a hack to make metrics re-usable through metaData (similar to https://nova.laravel.com/docs/3.0/filters/defining-filters.html#dynamic-filters )

**Comment by muzafferdede** [comment]
I have to spend full time even to think about for such a thing!  :) But i guess you are deeply involved on "Dashboard Softwares/Widgets". Things are not too familiar to me in use cases, but yeah, i would love to see how re-useable widgets would look like.

**Comment by muzafferdede** [comment]
@cord Ability for original request has been included in v1.0.3 now. You can use as:

```
new NovaGlobalFilter([
    // Filters
])->inline()->resettable(),
```

Let me know if all good. 

Cheers

**Comment by cord** [comment]
@muzafferdede just published https://github.com/Nova-BI/nova-databoards - would be great to get your feedback!

**Comment by muzafferdede** [comment]
@cord i am amazed what you put have together with this package. It is very promising solution to many dashboards. The only thing i see as hard is that it relays on many packages which will cause difficulties to maintain or add new functionalities unless if you convince other packages devs for the new features or ideas. But for foundation, it is great step to benefit other packages as you did. Hopefully you can gather some contributors and make this package awesome and unique.
