### ISSUE TITLE
Clearing filters

### ISSUE THREAD

**Issue by otrsw** [nemrutco/nova-global-filter#4]
Firstly - well done on a really well designed and useful package.  
One question from my side - is there a way to "clear" the filters?  
It would be great to have clear option on each dropdown or maybe even on the containing card?

**Comment by muzafferdede** [comment]
Thanks. 
Since this package broadcast the filter evenst, we can't really control other cards layout. But maybe there could be a clear button which could re-load filtered cards. Anyway this is on the roadmap.

**Comment by muzafferdede** [comment]
@otrsw v1.0.3 included this ability. Keep in mind that it's not a perfect solution but a 'better than nothing'. Cheers
